# Generated by Django 3.0.2 on 2020-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('Eletronico', 'ELETRONICO'), ('Automotivo', 'AUTOMOTIVO')], max_length=100),
        ),
    ]
